spring:
  profiles:
    active: @profileActive@

  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    favicon:
      enabled: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false

  http:
    converters:
      preferred-json-mapper: fastjson

http:
  encoding:
    charset:  UTF-8
    enabled:  true
    force:  true
  mappers:
    json-pretty-print:  true
  converters:
    preferred-json-mapper: fastjson


ebeans:
  dbName: db
  packages: com.zzsim.taxi.core.common.entitys
