spring:
  profiles:
    active: dev

  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    favicon:
      enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false
  http:
    converters:
      preferred-json-mapper: fastjson

http:
  encoding:
    charset:  UTF-8
    enabled:  true
    force:  true
  mappers:
    json-pretty-print:  true
  converters:
    preferred-json-mapper: fastjson


ebeans:
  dbName: db
  packages: com.zzsim.taxi.core.common.entitys
  
taxi:
  tempPath: /home/zzfz/mfs/static/taxi/temp/
  basePath: /home/zzfz/mfs/static/taxi/
  car: car/car/
  annualVerification: car/annualVerification/
  carOperateLog: car/carOperateLog/
  insurance: car/insurance/
  maintain: car/maintain/
  registerRecord: driver/registerRecord/
  checkReport: driver/checkReport/
  noCriminalRecord: driver/noCriminalRecord/
  serviceCommitment: driver/serviceCommitment/
  insuranceCommitment: driver/insuranceCommitment/
  IDCardImg: driver/IDCardImg/
  safetyResponsibility: driver/safetyResponsibility/
