server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: @profileActive@

  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    favicon:
      enabled: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false

  http:
    converters:
      preferred-json-mapper: fastjson

http:
  encoding:
    charset:  UTF-8
    enabled:  true
    force:  true
  mappers:
    json-pretty-print:  true
  converters:
    preferred-json-mapper: fastjson


ebeans:
  dbName: db
  packages: com.ys.common.entitys


swagger:
  enabled: true
  title: api
  description: api
  version: 1.0.0.RELEASE
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl: https://github.com/dyc87112/spring-boot-starter-swagger
  contact.name: zengyufei
  contact.url: http://blog.didispace.com
  contact.email: 31263620@qq.com
  base-package: com.ys.admin.controller
  base-path: /**
  exclude-path: /error, /ops/**

sys:
 token:
  timeout: 2 * 60 * 60
  liveTime: 1 * 60 * 60